### ISSUE TITLE
I am encountering an error while using the software.[Bug] 

### ISSUE THREAD

**Issue by chichi1314520** [HenestrosaDev/audiotext#38]
Traceback (most recent call last):
  File "handlers\whisperx_handler.py", line 53, in transcribe_file
  File "whisperx\alignment.py", line 73, in load_align_model
    align_model = bundle.get_model(dl_kwargs={"model_dir": model_dir}).to(device)
  File "torchaudio\pipelines\_wav2vec2\impl.py", line 126, in get_model
  File "torchaudio\pipelines\_wav2vec2\impl.py", line 202, in _get_state_dict
  File "torchaudio\pipelines\_wav2vec2\impl.py", line 89, in _get_state_dict
  File "torch\hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
![图片](https://github.com/HenestrosaDev/audiotext/assets/42328109/d9af3512-b12f-4c64-95c9-bd6a09e6f579)

**Comment by HenestrosaDev** [comment]
According to [this StackOverflow post](https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory), it appears that the model file is corrupted due to an incomplete download or an interruption in the process. Have you tried deleting the Audiotext folder and unzipping the `audiotext-v2.2.3.zip` again? If you have done so and still get the same error, can you try running Audiotext on a different computer? I've also read in [this GitHub issue](https://github.com/ultralytics/ultralytics/issues/5793) that it might be due to disk space issues that happen when saving model checkpoints.

**Comment by HenestrosaDev** [comment]
I closed the issue as no feedback was provided.
